### ISSUE TITLE
How to disable animations on origin page?

### ISSUE THREAD

**Issue by tobimori** [johannschopplich/kirby.tools#3]
### Describe the feature

I have some move in transitions on load and they will get retriggered each time the live preview reloads. How can I conditionally disable the animations in **my custom JS code** / check if the page is running inside live preview?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/kirby.tools/issues).

**Comment by johannschopplich** [comment]
Great idea. Will implement that. 👍

**Comment by johannschopplich** [comment]
With the release of v1.1.0+, you can now detect the preview mode in both backend and frontend code. There's a [dedicated documentation guide](https://kirby.tools/docs/live-preview/preview-mode).

In summary:

## Backend

The Kirby Live Preview provides a `previewMode` content key that you can use to detect whether the current page is in preview mode. The key is `true` if the page is in preview mode and undefined (`false`) otherwise:

```php
if ($page->previewMode()->isTrue()) {
  // Page is in preview mode
}
```

Wrap the HTML in your snippets and template that you want to hide in a conditional statement that checks if the `previewMode` key is `false`:

```html [site/snippets/footer.php]
<?php if ($page->previewMode()->isFalse()): ?>
<div class="cookie-banner">
  <p>This is hidden in preview mode</p>
</div>
<?php endif ?>
```

## Frontend

The same page rendered as a preview embeds a `data-preview-mode` attribute in the document element (`<html>` tag). You can use this attribute to hide or disable elements in your frontend code.

For example, you can hide the cookie banner with the following CSS:

```css [assets/css/main.css]
[data-preview-mode] .cookie-banner {
  display: none;
}
```

For JavaScript animations or other features, you can use the `data-preview-mode` attribute to disable them:

```js [assets/js/main.js]
const isPreviewMode = document.documentElement.dataset.previewMode;

if (!isPreviewMode) {
  // Run your animations or other features
}
```
